// Generated by CoffeeScript 1.12.7
(function() {
  require('seneca')().use('email_imp').listen({
    type: 'tcp',
    port: 3002,
    pin: 'area:email'
  });

}).call(this);

//# sourceMappingURL=email_service.js.map
