// Generated by CoffeeScript 1.12.7
(function() {
  var email, email_imp, server;

  email = require('emailjs');

  server = email.server.connect({
    user: "qqbao@fiberhome.com",
    password: "transformers747",
    host: "smtp.fiberhome.com",
    ssl: false
  });

  email_imp = function(options) {
    this.add({
      init: 'plugin'
    }, function(msg, respond) {
      console.log("email_plugin plugin loaded...");
      return respond();
    });
    return this.add({
      area: "email",
      action: "send"
    }, function(args, done) {
      console.log("email send...");
      return server.send({
        text: args.content,
        from: "qqbao@fiberhome.com",
        to: args.to,
        subject: args.subject
      }, function(err, message) {
        console.log(err || message);
        return done(err, message);
      });
    });
  };

  module.exports = email_imp;

}).call(this);

//# sourceMappingURL=email_imp.js.map
