// Generated by CoffeeScript 1.12.7
(function() {
  var front_end_api, promise;

  promise = require('bluebird');

  front_end_api = function(options) {
    var act, seneca;
    seneca = this;
    act = promise.promisify(seneca.act, {
      context: seneca
    });
    seneca.add({
      area: "ui",
      action: "products"
    }, function(args, done) {
      this.log.warn(this.fixedargs['tx$'] + "Load products list...");
      return act({
        area: "product",
        action: "fetch"
      }).then(function(result) {
        return done(null, result);
      })["catch"](function(err) {
        return done(err, null);
      });
    });
    seneca.add({
      area: "ui",
      action: "orders"
    }, function(args, done) {
      console.log("Load orders list...");
      return act({
        area: "orders",
        action: "fetch"
      }).then(function(result) {
        return done(null, result);
      })["catch"](function(err) {
        return done(err, null);
      });
    });
    seneca.add({
      area: "ui",
      action: "productbyid"
    }, function(args, done) {
      var id;
      console.log("Get product by id...");
      id = args.args.params.id;
      return act({
        area: "product",
        action: "fetch",
        criteria: "byId",
        id: id
      }).then(function(result) {
        return done(null, result);
      })["catch"](function(err) {
        return done(err, null);
      });
    });
    seneca.add({
      area: "ui",
      action: "createorder"
    }, function(args, done) {
      console.log("Create order...");
      return act({
        area: "product",
        action: "fetch",
        criteria: "byId",
        id: args.args.body.productid
      }).then(function(product) {
        return act({
          area: "orders",
          action: "create",
          products: [product],
          email: args.args.body.email,
          name: args.args.body.name
        }).then(function(order) {
          return done(null, order);
        })["catch"](function(err) {
          return done(err, null);
        });
      })["catch"](function(err) {
        return done(err, null);
      });
    });
    return this.add("init:front_end_api", function(msg, respond) {
      this.act('role:web', {
        routes: {
          prefix: '/api',
          pin: 'area:ui,action:*',
          map: {
            products: {
              GET: true
            },
            productbyid: {
              GET: true,
              suffix: '/:id'
            },
            orders: {
              GET: true
            },
            createorder: {
              POST: true
            }
          }
        }
      });
      return respond();
    });
  };

  module.exports = front_end_api;

}).call(this);

//# sourceMappingURL=front_end_api.js.map
