// Generated by CoffeeScript 1.12.7
(function() {
  var Express, Router, SenecaWeb, app, context, seneca, senecaWebConfig;

  SenecaWeb = require('seneca-web');

  Express = require('express');

  Router = Express.Router;

  context = new Router();

  senecaWebConfig = {
    context: context,
    adapter: require('seneca-web-adapter-express'),
    options: {
      parseBody: false
    }
  };

  app = Express().use(require('body-parser').json()).use(context).listen(3001);

  seneca = require('seneca')().use('entity').use(SenecaWeb, senecaWebConfig).use('front_end_api').client({
    type: 'tcp',
    host: '10.99.20.234',
    port: 3000,
    pin: 'area:product'
  }).client({
    type: 'tcp',
    host: '10.99.20.234',
    port: 3004,
    pin: 'area:orders'
  });

}).call(this);

//# sourceMappingURL=front_end.js.map
