// Generated by CoffeeScript 1.12.7
(function() {
  var product_ds;

  product_ds = function(options) {
    this.add({
      init: 'product_ds'
    }, function(msg, respond) {
      console.log("product_ds plugin loaded...");
      return respond();
    });
    this.add({
      area: "product",
      action: "fetch"
    }, function(args, done) {
      var products;
      console.log('fetch api call');
      products = this.make("products");
      return products.list$({}, function(err, result) {
        return done(err, result);
      });
    });
    this.add({
      area: "product",
      action: "fetch",
      criteria: "byCategory"
    }, function(args, done) {
      var products;
      console.log('fetch byCategory api call');
      products = this.make("products");
      return products.list$({
        category: args.category
      }, done);
    });
    this.add({
      area: "product",
      action: "fetch",
      criteria: "byId"
    }, function(args, done) {
      var product;
      console.log('fetch byId api call');
      product = this.make("products");
      return product.load$(args.id, done);
    });
    this.add({
      area: "product",
      action: "fetch",
      criteria: "byIdInner"
    }, function(args, done) {
      var product;
      console.log('fetch byId api call');
      product = this.make("products");
      return product.load$(args.id, done);
    });
    this.add({
      area: "product",
      action: "add"
    }, function(args, done) {
      var products;
      console.log('add api call');
      console.log(args.category);
      products = this.make("products");
      products.category = args.category;
      products.name = args.name;
      products.description = args.description;
      products.price = args.price;
      return products.save$(function(err, product) {
        return done(err, product.data$(false));
      });
    });
    this.add({
      area: "product",
      action: "remove"
    }, function(args, done) {
      var product;
      console.log('remove api call');
      product = this.make("products");
      return product.remove$(args.id, function(err) {}, done(err, null));
    });
    return this.add({
      area: "product",
      action: "edit"
    }, function(args, done) {
      console.log('edit api call');
      return this.act({
        area: "product",
        action: "fetch",
        criteria: "byIdInner",
        id: args.id
      }, function(err, result) {
        result.data$({
          name: args.name,
          category: args.category,
          description: args.description,
          price: args.price
        });
        return result.save$(function(err, product) {
          return done(err, product.data$(false));
        });
      });
    });
  };

  module.exports = product_ds;

}).call(this);

//# sourceMappingURL=product_ds.js.map
