// Generated by CoffeeScript 1.12.7
(function() {
  require('seneca')().use('entity').use('mongo-store', {
    uri: 'mongodb://10.99.20.234:27017/seneca'
  }).use('product_ds').listen({
    type: 'tcp',
    port: 3000,
    pin: 'area:product'
  });

}).call(this);

//# sourceMappingURL=products_service.js.map
